### PR TITLE
Correction of issue #12

### PR DESCRIPTION
**Pull request by sclayer**
Update the Package file for to remove the dependency of linux-4.4-latest from the packages rockpi4[a|b|c]-rk-ubootimg.

The following distribution were modified:
- Bionic Testing (arm64, armhf)
- Buster Testing (arm64, armhf)
- Focal Testing (arm64, armhf)
- Strech Testing (arm64, armhf)

Commit from 01/06:
- Control file of rockpi4c-rk-ubootimg deb file modified for focal-testing release

### CODE REVIEW

**Comment by MichaIng** [comment]
Note that while these `Packages` files are used by APT to check dependencies before downloading packages, the package control files themselves need to have this change as well, else APT would pull the packages but DPkg would then fail to install them as of unresolved dependencies 😉.

**Comment by sclayer** [comment]
Thank you very much for the info, I was not aware of it.
I guess I have to learn a bit the package structure and complete the correction. 😊

**Comment by MichaIng** [comment]
Aside, it's good to have some action here, hopefully it triggers some rebuilds from the Radxa team. I'm also have an issue open which currently breaks WireGuard module compilation (and others) on ROCK Pi S.

**Comment by sclayer** [comment]
I hope as well :)
I just bought a ROCK PI 4 C for a NAS, and the packages doesn't install due to that issue.

**Pull request closed without merging**
